### ISSUE TITLE
[내 여행] 탭 기본 컴포넌트 및 레이아웃 컴포넌트 만들기

### ISSUE THREAD

**Issue by yeodahui** [F-orever/gabozago_FE#1]
### Todos

- [x] 페이지 템플릿 컴포넌트 
- [x] 하단 네비게이션 컴포넌트
- [x] Button 컴포넌트
- [x] Search Input 컴포넌트
- [x] Heading 컴포넌트
- [x] 모달 컴포넌트
- [x] 팝업 컴포넌트
