### ISSUE TITLE
[내 여행, 일정 생성 후] 페이지 내 UI 컴포넌트 분리 및 퍼블리싱

### ISSUE THREAD

**Issue by yeodahui** [F-orever/gabozago_FE#13]
## Todos

아래 컴포넌트의 퍼블리싱을 진행,
기능을 개발해야 할 부분은 Todo로 남기겠습니다.

### 장소 추가하기 전
- [x] **일정 정보 및 편집**
- [x] 비었을 때 일정 목록
- [x] **장소 추가하기 버튼**
- [x] 알림

### 장소 추가 후 → 이슈 분리: #18 , #19 
- ~~**일정 정보 및 편집** - 메모도 넣어야함~~
- ~~**장소 추가하기 버튼**~~
- ~~지도 view~~
- ~~일정 필터~~
- ~~편집 버튼 -> 일정편집~~

### 일정 편집 모드 → 이슈 분리: #20 
- ~~일자별 장소 목록(선택)~~
- ~~날짜이동~~
- ~~밀어서 삭제 background~~
- ~~최하단 날짜 이동 및 삭제 버튼~~
- ~~close 버튼~~

### 메모하기 → 이슈 분리: #21 
- ~~뒤로가기 버튼~~
- ~~메모~~
- ~~저장~~
