### ISSUE TITLE
UX 관련 피드백 반영

### ISSUE THREAD

**Issue by SugarSyrup** [F-orever/gabozago_FE#179]
## TODOS

- [ ] 단일 장소 페이지 / 컴포넌트 내 스크랩 아이콘에 스크랩 유무에 따라 색상 채우기
    - [x] 장소 페이지내 스낵바 삭제
- [x] 비 회원 유저 플로우 관리
    - [x] 토스트바 띄우는 플로우 통일
    - [x] 토스트바 유지 시간 5초로 증가
- [x] 장소 - 내 일정에 추가 UI 에서 다른 일정의 Day를 선택하여도 기존 선택이 지워지지 않는 문제
- [x] 장소 검색 페이지의 “추가한 여행지를 포함한 콘텐츠 제공” → “제공” 빼기
- [x] 여행 일정 상세보기 - 뒤로가기 버튼 추가
