### ISSUE TITLE
스크랩 - 스크랩 북

### ISSUE THREAD

**Issue by yeodahui** [F-orever/gabozago_FE#39]
### TODO
- [x] 스크랩 데이터 구조 구상
- [x] route 추가
- [x] 여행기 / 여행장소 탭 나누기
- [x] 여행기 탭 폴더별 상세 보기 (필터 제외)
- [x] 여행장소 탭 상세보기

![Image](https://github.com/F-orever/gabozago_FE/assets/102221305/87de0206-6b08-40fd-a81d-bc8d97141d86)
