### ISSUE TITLE
[ 내 여행 생성, 검색, 마이페이지, 공통 컴포넌트 ] 오류 수정 및 리펙토링

### ISSUE THREAD

**Issue by SugarSyrup** [F-orever/gabozago_FE#46]
## Todos

**내 여행**

- [x] 홈 Post ThumbnailImg placeholder 이미지로 수정
- [x] Calendar 당일 치기 디자인 수정
- [x] Calendar for문 조건 수정
- [x] 지역 선택 시, 버튼 텍스트 수정

**검색**

- [x] 지역 선택에 따라 잘리는 부분 스크롤 가능하게 구현 ( 구현시, 바텀 nav 활용할 수 있는지 확인 )

**마이페이지**

- [x] offsetHeight 로 발생하는 여백 오류 수정
- [x] 팔로우 삭제 버튼, 내 페이지에서만 표기
- [x] 내 정보 수정 - Header padding 수정

**공통 컴포넌트**

- [x] Input padding style 수정
- [x] Input x 아이콘 선택시 onchange 동작안하는 버그 수정
- [x] Input Props로 색상 받기 ( background-color, color, border )
- [x] 공통 컴포넌트 Button Props 에 width 추가

**그 외**

- [x] [style] transition: ease-in-out으로 통일
