### ISSUE TITLE
Login/Signup Page

### ISSUE THREAD

**Issue by SugarSyrup** [F-orever/gabozago_FE#64]
### TODOS
- [x] 로그인 페이지
    - [x] 두가지 버튼 형태
    - [x] Animation Message Box
    - [x] 페이지 UI 및 기능 완성
- [x] 회원가입 페이지
    - [x] input + label
    - [x] checkbox + label
    - [x] form
    - [x] 페이지 UI 및 기능 완성 
- [x] 약관 페이지
    - [x] 페이지 템플릿
    - [x] 이용약관
    - [x] 개인정보 수집
    - [x] 위치 서비스
    - [x] 페이지 UI 및 기능 완성
